eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: library-system-admin
server:
  port: 8080
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 3000
logging:
  level:
    sale.ljw: debug