server:
  port: 80
spring:
  application:
    name: api-gateway-server
  cloud:
    # 网关配置
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors‐configurations:
          '[/**]': # 匹配所有请求
            # allowedOrigins: "*"
            allowedOriginPatterns: '*' #跨域处理 允许所有的域
            allowCredentials: true # 是否允许携带cookie
            allowedMethods: # 支持的方法
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
      # 路由配置
      routes: # 集合
        - id: library-system-admin
          uri: lb://library-system-admin
          predicates:
            - Path=/librarySystemAdmin/**
          filters:
            - StripPrefix= 1
            - name: RequestRateLimiter #请求数限流
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis‐rate‐limiter.replenishRate: 1 #令牌桶每秒填充平均速率
                redis‐rate‐limiter.burstCapacity: 1 #令牌桶总容量
        - id: library-system-reader
          uri: lb://library-system-reader
          predicates:
            - Path=/librarySystemReader/**
          filters:
            - StripPrefix= 1
      discovery:
        locator:
          enabled: true # 请求路径前可以添加微服务名称
          lower-case-service-id: true # 允许小写
  datasource:
    username: libraryManage
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: oN1jyw3r53806o5NcrNT
    url: jdbc:mysql://123.57.20.244:3306/libraryManage?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    #    ip数据库
    #    url: jdbc:mysql://123.57.20.244:3306/neusoftTest?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  redis:
      host: localhost
      jedis:
        pool:
          max-idle: 500
          max-wait: 100
          max-active: 1000
          min-idle: 100
      timeout: 1000
mybatis-plus:
    #配置MyBatis映射文件
    mapper-locations: classpath:/mapper/*.xml
    #配置MyBatis返回类型别名
    type-aliases-package: sale.ljw.backend.pojo
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      jdbc-type-for-null: 'null'
      default-statement-timeout: 3000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

