server:
  port: 80
spring:
  application:
    name: api-gateway-server
  cloud:
    # 网关配置
    gateway:
      globalcors:
        cors‐configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              ‐ GET
              ‐ POST
              ‐ PUT
              ‐ DELETE
      # 路由配置
      routes: # 集合
        - id: library-system-admin
          uri: lb://library-system-admin
          predicates:
            - Path=/librarySystemAdmin/**
          filters:
            - StripPrefix= 1
            - name: RequestRateLimiter #请求数限流
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis‐rate‐limiter.replenishRate: 1 #令牌桶每秒填充平均速率
                redis‐rate‐limiter.burstCapacity: 1 #令牌桶总容量
        - id: library-system-reader
          uri: lb://library-system-reader
          predicates:
            - Path=/librarySystemReader/**
          filters:
            - StripPrefix= 1
      discovery:
        locator:
          enabled: true # 请求路径前可以添加微服务名称
          lower-case-service-id: true # 允许小写
  redis:
    host: localhost
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

