#设置eureka基本信息
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
  servlet:
    context-path: /librarySystemReader
#设置feign的超时时长
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 3000
#配置hystrix熔断器
hystrix:
  metrics:
    enabled: true
logging:
  level:
    sale.ljw: debug
spring:
  mail:
    username: *** # 需修改
    password: *** # 需修改
    host: smtp.qq.com
    default-encoding: utf-8
  application:
    name: library-system-reader
  profiles:
    active: test
  cache:
    type: redis
    redis:
      time-to-live: 20000
      cache-null-values: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 10MB
  datasource:
    username: *** # 需修改
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: *** # 需修改
    url: jdbc:mysql://***/libraryManage?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    #    ip数据库
    #    url: jdbc:mysql://***Test?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  redis:
    host: localhost
    jedis:
      pool:
        max-idle: 500
        max-wait: 100
        max-active: 1000
        min-idle: 100
    timeout: 1000
  rabbitmq:
    port: 5672
    host: *** # 需修改
    username: *** # 需修改
    password: **** # 需修改
    virtual-host: /
mybatis-plus:
  #配置MyBatis映射文件
  mapper-locations: classpath:/mapper/*.xml
  #配置MyBatis返回类型别名
  type-aliases-package: sale.ljw.backend.pojo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    jdbc-type-for-null: 'null'
    default-statement-timeout: 3000
#      日志输出
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: ignored
page helper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
